version: '3.8'

services:
  user-management-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # Optional: Add external database for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: usermanagement
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
