name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Build + run tests
      - name: Build and Test with Maven
        run: mvn -B clean verify

      # 4️⃣ Optional: upload test results (nice for UI reporting)
      - name: Publish Test Results
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: junit
          cleanup: true
      
      - name: Publish Coverage Report
        uses: codecov/codecov-action@v4
        with:
          files: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
